# Кастомизация
homeassistant:
  customize:
    # Освещение
    light.kitchen:
      friendly_name: Кухня Люстра
      icon: mdi:ceiling-light


# Yeelight
yeelight:
  devices:
    192.168.1.x:
      name: kitchen


# Таймер
timer:
  light_kitchen_auto:
    duration: '00:00:02'
  light_kitchen_manual:
    duration: '01:30:00'


input_boolean:
  # Вкл / выкл автоматизации освещения
  light_kitchen_automation:
    name: Кухня
    initial: on
    icon: mdi:home-automation


# Автоматизации
automation:
  # Датчик движения
  - alias: light_kitchen_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_kitchen
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_kitchen
        to: 'off'
        for: '00:01:00'
      - platform: state
        entity_id: binary_sensor.motion_sensor_kitchen
        to: 'off'
        for: '00:05:00'
    condition:
      - "{{ is_state('timer.light_kitchen_manual', 'idle') }}"
    action:
      - choose:
          # Включение при обнаружении движения
          - conditions:
              - "{{ trigger.to_state.state == 'on' }}"
              - "{{ is_state('light.kitchen', 'off') }}"
              - "{{ states('sensor.outdoor_illuminance') | int < 2000 }}"
            sequence:
              - service: timer.start
                entity_id: timer.light_kitchen_auto
              - service: light.turn_on
                entity_id: light.kitchen
                data:
                  brightness_pct: >
                    {% if 0 <= now().hour < 7 %} 1
                    {% elif (22 <= now().hour < 24) or
                            ((7 <= now().hour < 9) and now().isoweekday() > 5) %} 10
                    {% elif ((7 <= now().hour < 22) and now().isoweekday() < 6) or
                            ((9 <= now().hour < 22) and now().isoweekday() > 5) %} 100
                    {% endif %}
                  color_temp: >
                    {% if 0 <= now().hour < 7 %} 588
                    {% else %} 250
                    {% endif %}
          # Выключение без движения
          - conditions:
              - "{{ trigger.to_state.state == 'off' }}"
              - "{{ is_state('light.kitchen', 'on') }}"
              - condition: or
                conditions:
                  - "{{ (0 <= now().hour < 6) and
                        (now() - states.binary_sensor.motion_sensor_kitchen.last_updated).seconds | int >= 60 }}"
                  - "{{ (6 <= now().hour < 24) and
                        (now() - states.binary_sensor.motion_sensor_kitchen.last_updated).seconds | int >= 300 }}"
            sequence:
              - service: timer.start
                entity_id: timer.light_kitchen_auto
              - service: light.turn_off
                entity_id: light.kitchen


  # Кнопка
  - alias: light_kitchen_smart_switch
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_kitchen
    condition:
      - "{{ trigger.event.data.event in [1002, 1004, 1001] }}"
    action:
      - choose:
          # Включение по одинарному клику
          - conditions:
              - "{{ trigger.event.data.event == 1002 }}"
              - "{{ is_state('light.kitchen', 'off') }}"
            sequence:
              - service: light.turn_on
                entity_id: light.kitchen
                data:
                  brightness_pct: >
                    {% if 7 <= now().hour < 22 %} 100
                    {% elif 22 <= now().hour < 24 %} 10
                    {% elif 0 <= now().hour < 7 %} 1
                    {% endif %}
                  color_temp: >
                    {% if 0 <= now().hour < 7 %} 588
                    {% else %} 250
                    {% endif %}
          # Включение 25% яркости по двойному клику
          - conditions:
              - "{{ trigger.event.data.event == 1004 }}"
              - "{{ state_attr('light.kitchen', 'brightness') | int != 64 }}"
            sequence:
              - service: light.turn_on
                entity_id: light.kitchen
                data: {brightness_pct: 25, color_temp: 250}
          # Включение 100% яркости по длинному нажатию
          - conditions:
              - "{{ trigger.event.data.event == 1001 }}"
              - "{{ state_attr('light.kitchen', 'brightness') | int != 255 }}"
            sequence:
              - service: light.turn_on
                entity_id: light.kitchen
                data: {brightness_pct: 100, color_temp: 250}
        # Выключение освещения при любом нажатии
        default:
          - service: light.turn_off
            entity_id: light.kitchen


  # Время
  - alias: light_kitchen_time
    initial_state: true
    trigger:
      - platform: time
        at:
          - '22:00:05'
          - '07:00:05'
    condition:
      - "{{ is_state('light.kitchen', 'on') }}"
    action:
      - service: timer.start
        entity_id: timer.light_kitchen_auto
      - choose:
          # Уменьшение яркости в заданное время
          - conditions:
              - "{{ trigger.now.hour == 22 }}"
              - "{{ is_state('timer.light_kitchen_manual', 'idle') }}"
            sequence:
              - service: light.turn_on
                entity_id: light.kitchen
                data: {brightness_pct: 10, color_temp: 250, transition: 3}
          # Увеличение яркости в заданное время
          - conditions:
              - "{{ trigger.now.hour == 7 }}"
              - "{{ now().isoweekday() < 6}}"
            sequence:
              - service: light.turn_on
                entity_id: light.kitchen
                data: {brightness_pct: 100, color_temp: 250, transition: 3}
