# Кастомизация
homeassistant:
  customize:
    # Подсветка Шлюза
    light.gateway_light:
      friendly_name: Подсветка Шлюза


# Автоматизации
automation:
  # Датчик движения
  - alias: light_gateway_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_hall
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_hall
        to: 'off'
        for: '00:01:00'
    condition:
      - "{{ '00:00' <= states('sensor.time') < states('sensor.sunrise_time') }}"
    action:
      - choose:
          # Включение подсветки шлюза по движению
          - conditions:
              - "{{ trigger.to_state.state == 'on' }}"
              - "{{ is_state('light.gateway_light', 'off') }}"
            sequence:
              - service: light.turn_on
                entity_id: light.gateway_light
                data: {brightness_pct: 2, rgb_color: [255, 130, 0]}
        default:
          # Выключение подсветки шлюза без движения
          - service: light.turn_off
            entity_id: light.gateway_light


  # Время
  - alias: light_gateway_time
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/5'
      - platform: time
        at: '23:00:05'
      - platform: sun
        event: sunrise
        offset: '+00:05:00'
    action:
      - choose:
          # Включение подсветки шлюза с рандомным цветом в заданное время
          - conditions:
              - condition: sun
                after: sunset
                after_offset: '-01:00:00'
              - condition: time
                before: '22:50:00'
              - "{{ trigger.platform == 'time_pattern' }}"
              - "{{ is_state('light.gateway_light', 'off') }}"
              - "{{ is_state('alarm_control_panel.ha_alarm', 'disarmed') }}"
            sequence:
              - service: light.turn_on
                entity_id: light.gateway_light
                data:
                  brightness_pct: 15
                  rgb_color: ['{{ (range(0, 255)|random) }}','{{ (range(0, 255)|random) }}','{{ (range(0, 255)|random) }}']
          # Выключение подсветки шлюза в заданное время
          - conditions:
              - "{{ is_state('light.gateway_light', 'on') }}"
              - condition: or
                conditions:
                  - "{{ trigger.platform == 'time' }}"
                  - "{{ trigger.platform == 'sun' }}"
            sequence:
              - service: light.turn_off
                entity_id: light.gateway_light
