# Автоматизация
automation:
  # Имитация присутствия
  - alias: light_fake_presence
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/5'
      - platform: state
        entity_id: script.light_fake_presence
        to: 'off'
        for: '00:10:00'
    condition:
      - "{{ is_state('alarm_control_panel.ha_alarm', 'armed_away') }}"
    action:
      - choose:
          - conditions:
              - "{{ trigger.platform == 'time_pattern' }}"
              - "{{ is_state('script.light_fake_presence', 'off') }}"
              - "{{ states('sensor.outdoor_illuminance') | int < 2000 }}"
            sequence:
              - service: script.turn_on
                entity_id: script.light_fake_presence
          - conditions:
              - "{{ trigger.platform == 'state' }}"
            sequence:
              - service: light.turn_off
                entity_id:
                  - light.kitchen
                  - light.livingroom_ceiling
                  - light.bedroom
                  - light.bathroom


# Скрипт
script:
  # Имитация присутствия
  light_fake_presence:
    sequence:
      - repeat:
          while:
            - condition: template
              value_template: "{{ states('sensor.outdoor_illuminance') | int < 2000 }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: >
                  {{ ['light.kitchen','light.livingroom_ceiling','light.bedroom','light.bathroom'] | random }}
                brightness_pct: 100
            - delay: '00:{{ (range(2, 15) | random) }}:00'
            - service: light.turn_off
              data:
                entity_id: >
                  {{ ['light.kitchen','light.livingroom_ceiling','light.bedroom','light.bathroom'] | random }}
            - delay: '00:{{ (range(1, 10) | random) }}:00'
