# Кастомизация
homeassistant:
  customize:
    # Освещение
    light.livingroom_ceiling:
      friendly_name: Зал Люстра
      icon: mdi:ceiling-light
    light.livingroom_floor:
      friendly_name: Зал Ночник
    light.livingroom_window:
      friendly_name: Зал Окно
      icon: mdi:lamp
    # Сцены освещения
    script.light_livingroom_bright:
      friendly_name: Сцена Ярко
      icon: mdi:brightness-7
    script.light_livingroom_movie:
      friendly_name: Сцена Кино
      icon: mdi:movie-roll
    script.light_livingroom_night:
      friendly_name: Сцена Ночь
      icon: mdi:weather-night


# Yeelight
yeelight:
  devices:
    192.168.1.x:
      name: livingroom_ceiling
    192.168.1.x:
      name: livingroom_floor


# Состояние подсветки ТВ (Osram Smart+ Led Strip BLE HomeKit). Группа в HomeKit
light:
  - platform: mqtt
    name: "Livingroom Led Strip"
    state_topic: "light/livingroom/led_strip/switch"
    command_topic: "light/livingroom/led_strip/switch"
    rgb_state_topic: "light/livingroom/led_strip/rgb"
    rgb_command_topic: "light/livingroom/led_strip/rgb"
    brightness_state_topic: "light/livingroom/led_strip/brightness"
    brightness_command_topic: "light/livingroom/led_strip/brightness"
    retain: true


# Таймеры
timer:
  light_livingroom_ceiling_auto:
    duration: '00:00:02'
  light_livingroom_floor_auto:
    duration: '00:00:02'
  light_livingroom_window_auto:
    duration: '00:00:02'
  light_livingroom_ceiling_manual:
    duration: '03:00:00'
  light_livingroom_floor_manual:
    duration: '03:00:00'
  light_livingroom_window_manual:
    duration: '03:00:00'


input_boolean:
  # Включение / выключение автоматизации освещения
  light_livingroom_automation:
    name: Зал
    initial: on
    icon: mdi:home-automation


# Скрипты
script:
  # Ярко
  light_livingroom_bright:
    sequence:
      - service: light.turn_on
        entity_id:
          - light.livingroom_ceiling
          - light.livingroom_floor
        data: {brightness_pct: 100, color_temp: 250}
      - service: timer.cancel
        entity_id:
          - timer.light_livingroom_ceiling_manual
          - timer.light_livingroom_floor_manual
      - service: timer.start
        entity_id:
          - timer.light_livingroom_ceiling_manual
          - timer.light_livingroom_floor_manual


  # Кино
  light_livingroom_movie:
    sequence:
      - service: light.turn_on
        entity_id:
          - light.livingroom_floor
          - light.livingroom_led_strip
        data: {brightness_pct: 15, transition: 3, rgb_color: [102, 102, 255]}
      - condition: state
        entity_id: light.livingroom_ceiling
        state: 'on'
      - service: light.turn_off
        entity_id: light.livingroom_ceiling
        data: {transition: 3}


  # Ночь
  light_livingroom_night:
    sequence:
      - service: light.turn_on
        entity_id: light.livingroom_floor
        data: {brightness_pct: 1, color_temp: 588, transition: 3}
      - condition: state
        entity_id: light.livingroom_ceiling
        state: 'on'
      - service: light.turn_off
        entity_id: light.livingroom_ceiling
        data: {transition: 3}


# Автоматизации
automation:
  # Кнопка
  - alias: light_livingroom_smart_switch
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_livingroom
    condition:
      - "{{ trigger.event.data.event in [1002, 1004, 1005, 1006, 1001] }}"
    action:
      - choose:
          # Включение люстры по одинарному клику
          - conditions:
              - "{{ trigger.event.data.event == 1002 }}"
              - "{{ is_state('light.livingroom_ceiling', 'off') }}"
            sequence:
              - service: light.turn_on
                entity_id: light.livingroom_ceiling
                data:
                  brightness_pct: >
                    {% if 0 <= now().hour < 8 %} 10
                    {% elif 8 <= now().hour < 21 %} 100
                    {% elif 21 <= now().hour < 24 %} 50
                    {% endif %}
                  color_temp: 250
          # Выключение люстры по одинарному клику
          - conditions:
              - "{{ trigger.event.data.event == 1002 }}"
              - "{{ is_state('light.livingroom_ceiling', 'on') }}"
            sequence:
              - service: light.turn_off
                entity_id: light.livingroom_ceiling
          # Включение ночника по двойному клику
          - conditions:
              - "{{ trigger.event.data.event == 1004 }}"
              - "{{ is_state('light.livingroom_floor', 'off') }}"
            sequence:
              - service: light.turn_on
                entity_id: light.livingroom_floor
                data:
                  brightness_pct: >
                    {% if (0 <= now().hour < 8) or (21 <= now().hour < 24) %} 10
                    {% elif 8 <= now().hour < 21 %} 100
                    {% endif %}
                  color_temp: 250
          # Выключение ночника по двойному клику
          - conditions:
              - "{{ trigger.event.data.event == 1004 }}"
              - "{{ is_state('light.livingroom_floor', 'on') }}"
            sequence:
              - service: light.turn_off
                entity_id: light.livingroom_floor
          # Вкл / Выкл подсветки ТВ по тройному клику
          - conditions: "{{ trigger.event.data.event == 1005 }}"
            sequence:
              - entity_id: light.livingroom_led_strip
                service: >
                  {% if is_state('light.livingroom_led_strip', 'off') %} light.turn_on
                  {% else %} light.turn_off
                  {% endif %}
          # Вкл / Выкл ночника на окне по четверному клику
          - conditions: "{{ trigger.event.data.event == 1006 }}"
            sequence:
              - entity_id: light.livingroom_window
                service: >
                  {% if is_state('light.livingroom_window', 'off') %} light.turn_on
                  {% else %} light.turn_off
                  {% endif %}
          # Включение группы по длинному нажатию
          - conditions:
              - "{{ trigger.event.data.event == 1001 }}"
              - condition: or
                conditions:
                  - "{{ is_state('light.livingroom_ceiling', 'off') }}"
                  - "{{ is_state('light.livingroom_floor', 'off') }}"
                  - "{{ is_state('light.livingroom_ceiling', 'off') and
                        is_state('light.livingroom_floor', 'off') }}"
            sequence:
              - service: script.turn_on
                entity_id: script.light_livingroom_bright
          # Выключение группы по длинному нажатию
          - conditions:
              - "{{ trigger.event.data.event == 1001 }}"
              - "{{ is_state('light.livingroom_ceiling', 'on') }}"
              - "{{ is_state('light.livingroom_floor', 'on') }}"
            sequence:
              - service: light.turn_off
                entity_id:
                  - light.livingroom_ceiling
                  - light.livingroom_floor
                  - light.livingroom_led_strip


  # Время
  - alias: light_livingroom_time
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/5'
      - platform: time
        at:
          - '21:30:05'
          - '23:00:05'
    action:
      - choose:
          # Включение в заданное время при низкой освещенности
          - conditions:
              - "{{ trigger.platform == 'time_pattern' }}"
              - "{{ is_state('alarm_control_panel.ha_alarm', 'disarmed') }}"
              - "{{ states('sensor.outdoor_illuminance') | int < 1000 }}"
              - condition: sun
                after: sunset
                after_offset: '-00:30:00'
              - condition: time
                before: '22:50:00'
              - condition: or
                conditions:
                  - "{{ is_state('light.livingroom_floor', 'off') and
                        is_state('timer.light_livingroom_floor_manual', 'idle') }}"
                  - "{{ is_state('light.livingroom_window', 'off') and
                        is_state('timer.light_livingroom_window_manual', 'idle') }}"
            sequence:
              - service: timer.start
                entity_id:
                  - timer.light_livingroom_floor_auto
                  - timer.light_livingroom_window_auto
              # Ночник
              - service: light.turn_on
                data:
                  entity_id: >
                    {% if is_state('light.livingroom_floor', 'on') %} light.none
                    {% else %} light.livingroom_floor
                    {% endif %}
                  brightness_pct: 1
                  color_temp: 250
                  transition: 3
              # Ночник на окне
              - service: light.turn_on
                data:
                  entity_id: >
                    {% if is_state('light.livingroom_window', 'on') %} light.none
                    {% else %} light.livingroom_window
                    {% endif %}
                  brightness_pct: 50
          # Выключение в заданное время
          - conditions:
              - "{{ trigger.platform == 'time' and trigger.now.minute == 0 }}"
              - condition: or
                conditions:
                  - "{{ is_state('light.livingroom_window', 'on') and
                        is_state('timer.light_livingroom_window_manual', 'idle') }}"
                  - "{{ is_state('light.livingroom_floor', 'on') and
                        is_state('timer.light_livingroom_floor_manual', 'idle') }}"
            sequence:
              - service: timer.start
                entity_id:
                  - timer.light_livingroom_floor_auto
                  - timer.light_livingroom_window_auto
              # Ночник
              - service: light.turn_off
                data:
                  entity_id: >
                    {% if is_state('light.livingroom_floor', 'on') %} light.livingroom_floor
                    {% else %} light.none
                    {% endif %}
              # Ночник на окне
              - service: light.turn_off
                data:
                  entity_id: >
                    {% if is_state('light.livingroom_window', 'on') %} light.livingroom_window
                    {% else %} light.none
                    {% endif %}
          # Уменьшение яркости в заданное время
          - conditions:
              - "{{ trigger.platform == 'time' and trigger.now.minute == 30 }}"
              - condition: or
                conditions:
                  - "{{ is_state('light.livingroom_ceiling', 'on') and
                        is_state('timer.light_livingroom_ceiling_manual', 'idle') and
                        (state_attr('light.livingroom_ceiling', 'brightness') | int > 64) }}"
                  - "{{ is_state('light.livingroom_window', 'on') and
                        is_state('timer.light_livingroom_window_manual', 'idle') and
                        (state_attr('light.livingroom_window', 'brightness') | int > 64) }}"
            sequence:
              - service: timer.start
                entity_id:
                  - timer.light_livingroom_ceiling_auto
                  - timer.light_livingroom_window_auto
              # Люстра
              - service: light.turn_on
                data:
                  entity_id: >
                    {% if is_state('light.livingroom_ceiling', 'on') %} light.livingroom_ceiling
                    {% else %} light.none
                    {% endif %}
                  brightness_pct: 25
              # Ночник на окне
              - service: light.turn_on
                data:
                  entity_id: >
                    {% if is_state('light.livingroom_window', 'on') %} light.livingroom_window
                    {% else %} light.none
                    {% endif %}
                  brightness_pct: 25
