# Кастомизация
homeassistant:
  customize:
    # Освещение
    light.bedroom:
      friendly_name: Спальня Люстра
      icon: mdi:ceiling-light


# Yeelight
yeelight:
  devices:
    192.168.1.x:
      name: bedroom


# Таймеры
timer:
  light_bedroom_auto:
    duration: '00:00:02'
  light_bedroom_manual:
    duration: '01:30:00'


input_boolean:
  # Вкл / Выкл автоматизации освещения
  light_bedroom_automation:
    name: Спальня
    initial: on
    icon: mdi:home-automation


# Автоматизации
automation:
  # Датчик движения
  - alias: light_bedroom_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_bedroom
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_bedroom
        to: 'off'
        for: '00:02:00'
    condition:
      - "{{ is_state('timer.light_bedroom_manual', 'idle') }}"
    action:
      - choose:
          # Включение при обнаружении движения
          - conditions:
              - "{{ trigger.to_state.state == 'on' }}"
              - "{{ is_state('light.bedroom', 'off') }}"
              - "{{ states('sensor.outdoor_illuminance') | int < 2000 }}"
              - condition: or
                conditions:
                  - "{{ (8 <= now().hour < 22) and now().isoweekday() < 6 }}"
                  - "{{ (10 <= now().hour < 22) and now().isoweekday() > 5 }}"
            sequence:
              - service: timer.start
                entity_id: timer.light_bedroom_auto
              - service: light.turn_on
                entity_id: light.bedroom
                data:
                  brightness_pct: >
                    {% if 8 <= now().hour < 21 %} 100
                    {% elif 21 <= now().hour < 22 %} 10
                    {% endif %}
                  color_temp: 250
          # Выключение без движения
          - conditions:
              - "{{ trigger.to_state.state == 'off' }}"
              - "{{ is_state('light.bedroom', 'on') }}"
            sequence:
              - service: timer.start
                entity_id: timer.light_bedroom_auto
              - service: light.turn_off
                entity_id: light.bedroom


  # Кнопка
  - alias: light_bedroom_smart_switch
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: smart_switch_bedroom
    condition:
      - "{{ trigger.event.data.event in [1002, 1004, 1001] }}"
    action:
      - choose:
          # Включение по одинарному клику
          - conditions:
              - "{{ trigger.event.data.event == 1002 }}"
              - "{{ is_state('light.bedroom', 'off') }}"
            sequence:
              - service: light.turn_on
                entity_id: light.bedroom
                data:
                  brightness_pct: >
                    {% if 0 <= now().hour < 6 %} 1
                    {% elif (6 <= now().hour < 8) or (21 <= now().hour < 24) %} 10
                    {% elif 8 <= now().hour < 21 %} 100
                    {% endif %}
                  color_temp: 250
          # Включение 25% яркости по двойному клику
          - conditions:
              - "{{ trigger.event.data.event == 1004 }}"
              - "{{ state_attr('light.bedroom', 'brightness') | int != 64 }}"
            sequence:
              - service: light.turn_on
                entity_id: light.bedroom
                data: {brightness_pct: 25, color_temp: 250}
          # Включение 100% яркости по длинному нажатию
          - conditions:
              - "{{ trigger.event.data.event == 1001 }}"
              - "{{ state_attr('light.bedroom', 'brightness') | int != 255 }}"
            sequence:
              - service: light.turn_on
                entity_id: light.bedroom
                data: {brightness_pct: 100, color_temp: 250}
        # Выключение освещения при любом нажатии
        default:
          - service: light.turn_off
            entity_id: light.bedroom


  # Время
  - alias: light_bedroom_time
    initial_state: true
    trigger:
      - platform: time
        at:
          - '21:00:05'
          - '10:00:05'
    condition:
      - "{{ is_state('light.bedroom', 'on') }}"
    action:
      # Уменьшение / Увеличение яркости в заданное время
      - service: timer.start
        entity_id: timer.light_bedroom_auto
      - service: light.turn_on
        entity_id: light.bedroom
        data:
          color_temp: 250
          transition: 3
          brightness_pct: >
            {% if trigger.now.hour == 21 %} 10
            {% elif trigger.now.hour == 10 %} 100
            {% endif %}
