# Кастомизация
homeassistant:
  customize:
    # Освещение
    light.hall_1:
      friendly_name: Холл-1
    light.hall_2:
      friendly_name: Холл-2
    light.hall:
      friendly_name: Холл Люстра
      icon: mdi:ceiling-light


# Yeelight
yeelight:
  devices:
    192.168.1.x:
      name: hall_1
    192.168.1.x:
      name: hall_2


# Группа
light:
  - platform: group
    name: Hall
    entities:
      - light.hall_1
      - light.hall_2


# Таймер
timer:
  light_hall_auto:
    duration: '00:00:02'
  light_hall_manual:
    duration: '01:00:00'


input_boolean:
  # Вкл / выкл автоматизации освещения
  light_hall_automation:
    name: Холл
    initial: on
    icon: mdi:home-automation


# Автоматизации
automation:
  # Датчик движения
  - alias: light_hall_motion
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_sensor_hall
        to: 'on'
      - platform: state
        entity_id: binary_sensor.motion_sensor_hall
        to: 'off'
        for: '00:01:00'
    condition:
      - "{{ is_state('timer.light_hall_manual', 'idle') }}"
    action:
      - choose:
          # Включение при обнаружении движения
          - conditions:
              - "{{ trigger.to_state.state == 'on' }}"
              - "{{ is_state('light.hall', 'off') }}"
              - condition: or
                conditions:
                  - "{{ (6 <= now().hour < 23) and now().isoweekday() < 6 }}"
                  - "{{ (9 <= now().hour < 22) and now().isoweekday() > 5 }}"
            sequence:
              - service: timer.start
                entity_id: timer.light_hall_auto
              - service: light.turn_on
                entity_id: light.hall
                data:
                  brightness_pct: >
                    {% if 6 <= now().hour < 8 %} 10
                    {% elif 8 <= now().hour < 21 %} 100
                    {% elif 21 <= now().hour < 23 %} 1
                    {% endif %}
          # Выключение без движения
          - conditions:
              - "{{ trigger.to_state.state == 'off' }}"
              - "{{ is_state('light.hall', 'on') }}"
            sequence:
              - service: timer.start
                entity_id: timer.light_hall_auto
              - service: light.turn_off
                entity_id: light.hall


  # Диммер
  - alias: light_hall_dimmer
    initial_state: true
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: tradfri_wireless_dimmer
    condition:
      - "{{ trigger.event.data.event in [1002, 4002] }}"
    action:
      - choose:
          # Включение диммером днем
          - conditions:
              - "{{ trigger.event.data.event == 1002 }}"
              - "{{ is_state('light.hall', 'off') }}"
              - "{{ 6 <= now().hour < 23 }}"
            sequence:
              - service: light.turn_on
                entity_id: light.hall
                data: {brightness_pct: 100}
          # Включение диммером ночью
          - conditions:
              - "{{ trigger.event.data.event == 1002 }}"
              - condition: or
                conditions:
                  - "{{ now().hour == 23 }}"
                  - "{{ 0 <= now().hour < 6 }}"
            sequence:
              - service: light.turn_on
                entity_id: light.hall
                data:
                  brightness: >
                    {% if is_state('light.hall', 'off') %} 3
                    {% else %}
                      {% set bri = state_attr('light.hall', 'brightness') | int %}
                        {{ [bri+123, 249] | min }}
                    {% endif %}
          # Выключение диммером
          - conditions:
              - "{{ trigger.event.data.event == 4002 }}"
              - "{{ is_state('light.hall', 'on') }}"
            sequence:
              - service: light.turn_off
                entity_id: light.hall


  # Время
  - alias: light_hall_time
    initial_state: true
    trigger:
      - platform: time
        at:
          - '21:00:05'
          - '08:00:05'
    condition:
      - "{{ is_state('light.hall', 'on') }}"
    action:
      # Уменьшение / Увеличение яркости в заданное время
      - service: timer.start
        entity_id: timer.light_hall_auto
      - service: light.turn_on
        entity_id: light.hall
        data:
          transition: 3
          brightness_pct: >
            {% if trigger.now.hour == 21 %} 1
            {% elif trigger.now.hour == 8 %} 100
            {% endif %}
