# Кастомизация
homeassistant:
  customize:
    sensor.battery_level_card_header:
      friendly_name: Состояние батареи датчиков
      icon: mdi:car-battery
    sensor.front_door_sensor_battery_level:
      friendly_name: Входная дверь
      icon: mdi:door
    sensor.motion_sensor_hall_battery_level:
      friendly_name: Холл ДД
      icon: mdi:run-fast
    sensor.motion_sensor_livingroom_battery_level:
      friendly_name: Зал ДД
      icon: mdi:run-fast
    sensor.motion_sensor_kitchen_battery_level:
      friendly_name: Кухня ДД
      icon: mdi:run-fast
    sensor.motion_sensor_bathroom_battery_level:
      friendly_name: Ванная ДД
      icon: mdi:run-fast
    sensor.motion_sensor_bedroom_battery_level:
      friendly_name: Спальня ДД
      icon: mdi:run-fast
    sensor.climate_sensor_livingroom_battery_level:
      friendly_name: Зал Климат
      icon: mdi:thermometer
    sensor.tradfri_wireless_dimmer_battery_level:
      friendly_name: Холл Диммер
      icon: mdi:power-off
    sensor.smart_switch_alarm_battery_level:
      friendly_name: Охрана Кнопка
      icon: mdi:power
    sensor.smart_switch_bedroom_battery_level:
      friendly_name: Спальня Кнопка
      icon: mdi:power
    sensor.smart_switch_bathroom_battery_level:
      friendly_name: Ванная Кнопка
      icon: mdi:power
    sensor.smart_switch_livingroom_battery_level:
      friendly_name: Зал Кнопка
      icon: mdi:power
    sensor.smart_switch_kitchen_battery_level:
      friendly_name: Кухня Кнопка
      icon: mdi:power


# Группа
group:
  # Сенсоры уровня заряда батареи датчиков
  battery_levels:
    name: Уровень заряда батареи
    entities:
      - sensor.front_door_sensor_battery_level
      - sensor.motion_sensor_hall_battery_level
      - sensor.motion_sensor_livingroom_battery_level
      - sensor.motion_sensor_kitchen_battery_level
      - sensor.motion_sensor_bedroom_battery_level
      - sensor.motion_sensor_bathroom_battery_level
      - sensor.smart_switch_alarm_battery_level
      - sensor.smart_switch_bathroom_battery_level
      - sensor.smart_switch_livingroom_battery_level
      - sensor.smart_switch_kitchen_battery_level
      - sensor.smart_switch_bedroom_battery_level
      - sensor.tradfri_wireless_dimmer_battery_level
      - sensor.climate_sensor_livingroom_battery_level


# Заголовок карты
sensor:
  - platform: template
    sensors:
      battery_level_card_header:
        value_template: ' '


# Автоматизации
automation:
  # Уведомление о низком уровне заряда батареи датчиков
  - alias: alert_battery_level
    initial_state: true
    trigger:
      - platform: time
        at: '10:00:05'
      - platform: time
        at: '18:00:05'
    condition:
        - condition: template
          value_template: >-
            {% for entity_id in states.group.battery_levels.attributes.entity_id if states(entity_id) | int < 10 %}
            {%- if loop.first -%}
            {{ true }}
            {%- endif -%}
            {% endfor %}
    action:
      - service: notify.ios_alert_battery_level
        data:
          title: 'Низкий уровень заряда!'
          message: >-
            {% set output = '' %}
            {% for entity_id in states.group.battery_levels.attributes.entity_id -%}
            {%- set itemData = entity_id.split('.') -%}
            {%- set friendly_name = states[itemData[0]][itemData[1]].attributes.friendly_name -%}
            {%- if states(entity_id) | int < 10 -%}
            {%- set output = output +friendly_name+' '+states(entity_id) +'%.                 ' -%}
            {{ output }}
            {%- endif -%}
            {% endfor %}
          data:
            push:
              sound: battery.m4r
              badge: 0
