# Кастомизация
homeassistant:
  customize:
    # Сенсоры энергопотребления
    sensor.energy_monthly_smart_plug_bedroom:
      friendly_name: Розетка
    sensor.energy_monthly_smart_plug_camera:
      friendly_name: Камера
    sensor.energy_monthly_light_hall_1:
      friendly_name: Холл-1
    sensor.energy_monthly_light_hall_2:
      friendly_name: Холл-2
    sensor.energy_monthly_light_livingroom_ceiling:
      friendly_name: Зал Люстра
    sensor.energy_monthly_light_livingroom_floor:
      friendly_name: Зал Ночник
    sensor.energy_monthly_light_livingroom_window:
      friendly_name: Зал Окно
    sensor.energy_monthly_light_kitchen:
      friendly_name: Кухня Люстра
    sensor.energy_monthly_light_bedroom:
      friendly_name: Спальня Люстра
    sensor.energy_monthly_light_bathroom:
      friendly_name: Ванная Плафон
    sensor.energy_monthly_total:
      friendly_name: Энергопотребление за месяц
    # За год
    sensor.energy_yearly_total:
      friendly_name: За год

    # Сенсоры потребляемой мощности
    sensor.power_total:
      friendly_name: Потребляемая мощность
      icon: mdi:flash-circle
    sensor.power_smart_plug_bedroom:
      icon: mdi:power-socket-eu
      friendly_name: Розетка
    sensor.power_smart_plug_camera:
      icon: mdi:cctv
      friendly_name: Камера
    sensor.power_light_hall_1:
      icon: mdi:lightbulb
      friendly_name: Холл-1
    sensor.power_light_hall_2:
      icon: mdi:lightbulb
      friendly_name: Холл-2
    sensor.power_light_livingroom_ceiling:
      icon: mdi:ceiling-light
      friendly_name: Зал Люстра
    sensor.power_light_livingroom_floor:
      icon: mdi:lightbulb
      friendly_name: Зал Ночник
    sensor.power_light_livingroom_window:
      icon: mdi:lamp
      friendly_name: Зал Окно
    sensor.power_light_kitchen:
      icon: mdi:ceiling-light
      friendly_name: Кухня Люстра
    sensor.power_light_bedroom:
      icon: mdi:ceiling-light
      friendly_name: Спальня Люстра
    sensor.power_light_bathroom:
      icon: mdi:lightbulb
      friendly_name: Ванная Плафон

    # Счетчики
    sensor.power_mqtt_total_m1:
      friendly_name: Январь
      icon: mdi:counter
    sensor.power_mqtt_total_m2:
      friendly_name: Февраль
      icon: mdi:counter
    sensor.power_mqtt_total_m3:
      friendly_name: Март
      icon: mdi:counter
    sensor.power_mqtt_total_m4:
      friendly_name: Апрель
      icon: mdi:counter
    sensor.power_mqtt_total_m5:
      friendly_name: Май
      icon: mdi:counter
    sensor.power_mqtt_total_m6:
      friendly_name: Июнь
      icon: mdi:counter
    sensor.power_mqtt_total_m7:
      friendly_name: Июль
      icon: mdi:counter
    sensor.power_mqtt_total_m8:
      friendly_name: Август
      icon: mdi:counter
    sensor.power_mqtt_total_m9:
      friendly_name: Сентябрь
      icon: mdi:counter
    sensor.power_mqtt_total_m10:
      friendly_name: Октябрь
      icon: mdi:counter
    sensor.power_mqtt_total_m11:
      friendly_name: Ноябрь
      icon: mdi:counter
    sensor.power_mqtt_total_m12:
      friendly_name: Декабрь
      icon: mdi:counter


# Сенсоры
sensor:
  # Потребление
  # Розетка / потребляемая мощность
  - platform: template
    sensors:
      power_smart_plug_bedroom:
        value_template: >
          {% if is_state('sensor.smart_plug_power_bedroom', 'unknown') %} 0.0
          {% else %}
            {{ states('sensor.smart_plug_power_bedroom') | float }}
          {% endif %}
        icon_template: mdi:power-plug
        unit_of_measurement: 'W'
  # Розетка / энергопотребление
  - platform: integration
    source: sensor.power_smart_plug_bedroom
    name: "consumption_smart_plug_bedroom"
    unit_prefix: k
  # Камера / потребляемая мощность
  - platform: template
    sensors:
      power_smart_plug_camera:
        value_template: >
          {% if is_state('sensor.smart_plug_power_camera', 'unknown') %} 0.0
          {% else %}
            {{ states('sensor.smart_plug_power_camera') | float }}
          {% endif %}
        icon_template: mdi:power-plug
        unit_of_measurement: 'W'
  # Камера / энергопотребление
  - platform: integration
    source: sensor.power_smart_plug_camera
    name: "consumption_smart_plug_camera"
    unit_prefix: k
  # Холл 1 / Yeelight White bulb / потребляемая мощность
  - platform: template
    sensors:
      power_light_hall_1:
        value_template: >
          {% if is_state('light.hall_1', 'on') %}
            {% set bri = (state_attr('light.hall_1', 'brightness') | int / 2.55) | round(0) %}
              {{ (8.1 - ((100 - bri) * (8.1 - 0.9) / 99)) | round(1) }}
          {% elif is_state('light.hall_1', 'off') %} 0.9
          {% else %} 0.0
          {% endif %}
        icon_template: mdi:lightbulb
        unit_of_measurement: 'W'
  # Холл 1 / Yeelight White bulb / энергопотребление
  - platform: integration
    source: sensor.power_light_hall_1
    name: "consumption_light_hall_1"
    unit_prefix: k
  # Холл 2 / Yeelight White bulb / потребляемая мощность
  - platform: template
    sensors:
      power_light_hall_2:
        value_template: >
          {% if is_state('light.hall_2', 'on') %}
            {% set bri = (state_attr('light.hall_2', 'brightness') | int / 2.55) | round(0) %}
              {{ (8.1 - ((100 - bri) * (8.1 - 0.9) / 99)) | round(1) }}
          {% elif is_state('light.hall_2', 'off') %} 0.9
          {% else %} 0.0
          {% endif %}
        icon_template: mdi:lightbulb
        unit_of_measurement: 'W'
  # Холл 2 / Yeelight White bulb / энергопотребление
  - platform: integration
    source: sensor.power_light_hall_2
    name: "consumption_light_hall_2"
    unit_prefix: k
  # Зал Люстра / Yeelight RGB bulb 4000K / потребляемая мощность
  - platform: template
    sensors:
      power_light_livingroom_ceiling:
        value_template: >
          {% if is_state('light.livingroom_ceiling', 'on') %}
            {% set bri = (state_attr('light.livingroom_ceiling', 'brightness') | int / 2.55) | round(0) %}
              {{ (9.4 - ((100 - bri) * (9.4 - 1.9) / 99)) | round(1) }}
          {% elif is_state('light.livingroom_ceiling', 'off') %} 1.3
          {% else %} 0.0
          {% endif %}
        icon_template: mdi:ceiling-light
        unit_of_measurement: 'W'
  # Зал Люстра / Yeelight RGB bulb 4000K / энергопотребление
  - platform: integration
    source: sensor.power_light_livingroom_ceiling
    name: "consumption_light_livingroom_ceiling"
    unit_prefix: k
  # Зал Ночник / Yeelight RGB bulb 4000K / потребляемая мощность
  - platform: template
    sensors:
      power_light_livingroom_floor:
        value_template: >
          {% if is_state('light.livingroom_floor', 'on') %}
            {% set bri = (state_attr('light.livingroom_floor', 'brightness') | int / 2.55) | round(0) %}
              {{ (9.4 - ((100 - bri) * (9.4 - 1.9) / 99)) | round(1) }}
          {% elif is_state('light.livingroom_floor', 'off') %} 1.3
          {% else %} 0.0
          {% endif %}
        icon_template: mdi:lightbulb
        unit_of_measurement: 'W'
  # Зал Ночник / Yeelight RGB bulb 4000K / энергопотребление
  - platform: integration
    source: sensor.power_light_livingroom_floor
    name: "consumption_light_livingroom_floor"
    unit_prefix: k
  # Зал Окно / TRÅDFRI bulb E14 W op/ch 400lm / потребляемая мощность
  - platform: template
    sensors:
      power_light_livingroom_window:
        value_template: >
          {% if is_state('light.livingroom_window', 'on') %}
            {% set bri = (state_attr('light.livingroom_window', 'brightness') | int / 2.55) | round(0) %}
              {% if bri >= 1 and bri <= 30 %}
                {{ (1.1 - ((30 - bri) * (1.1 - 0.7) / 29)) | round(1) }}
              {% elif bri > 30 and bri <= 60 %}
                {{ (2.0 - ((60 - bri) * (2.0 - 1.10) / 30)) | round(1) }}
              {% elif bri > 60 and bri <= 80 %}
                {{ (3.3 - ((80 - bri) * (3.3 - 2.0) / 20)) | round(1) }}
              {% elif bri > 80 and bri <= 100 %}
                {{ (5.4 - ((100 - bri) * (5.4 - 3.3) / 20)) | round(1) }}
              {% endif %}
          {% elif is_state('light.livingroom_window', 'off') %} 0.4
          {% else %} 0.0
          {% endif %}
        icon_template: mdi:lamp
        unit_of_measurement: 'W'
  # Зал Окно / TRÅDFRI bulb E14 W op/ch 400lm / энергопотребление
  - platform: integration
    source: sensor.power_light_livingroom_window
    name: "consumption_light_livingroom_window"
    unit_prefix: k
  # Кухня Люстра / Yeelight RGB bulb 4000K / потребляемая мощность
  - platform: template
    sensors:
      power_light_kitchen:
        value_template: >
          {% if is_state('light.kitchen', 'on') %}
            {% set bri = (state_attr('light.kitchen', 'brightness') | int / 2.55) | round(0) %}
              {{ (9.4 - ((100 - bri) * (9.4 - 1.9) / 99)) | round(1) }}
          {% elif is_state('light.kitchen', 'off') %} 1.3
          {% else %} 0.0
          {% endif %}
        icon_template: mdi:ceiling-light
        unit_of_measurement: 'W'
  # Кухня Люстра / Yeelight RGB bulb 4000K / энергопотребление
  - platform: integration
    source: sensor.power_light_kitchen
    name: "consumption_light_kitchen"
    unit_prefix: k
  # Спальня Люстра / Yeelight RGB bulb 4000K / потребляемая мощность
  - platform: template
    sensors:
      power_light_bedroom:
        value_template: >
          {% if is_state('light.bedroom', 'on') %}
            {% set bri = (state_attr('light.bedroom', 'brightness') | int / 2.55) | round(0) %}
              {{ (9.4 - ((100 - bri) * (9.4 - 1.9) / 99)) | round(1) }}
          {% elif is_state('light.bedroom', 'off') %} 1.3
          {% else %} 0.0
          {% endif %}
        icon_template: mdi:ceiling-light
        unit_of_measurement: 'W'
  # Спальня Люстра / Yeelight RGB bulb 4000K / энергопотребление
  - platform: integration
    source: sensor.power_light_bedroom
    name: "consumption_light_bedroom"
    unit_prefix: k
  # Ванная Плафон / TRÅDFRI bulb E27 opal 1000lm / потребляемая мощность
  - platform: template
    sensors:
      power_light_bathroom:
        value_template: >
          {% if is_state('light.bathroom', 'on') %}
            {% set bri = (state_attr('light.bathroom', 'brightness') | int / 2.55) | round(0) %}
              {% if bri >= 1 and bri < 5 %}
                1.0
              {% elif bri >= 5 and bri <= 40 %}
                {{ (2.6 - ((40 - bri) * (2.6 - 1.2) / 35)) | round(1) }}
              {% elif bri > 40 and bri <= 55 %}
                {{ (3.8 - ((55 - bri) * (3.8 - 2.6) / 15)) | round(1) }}
              {% elif bri > 55 and bri <= 70 %}
                {{ (5.8 - ((70 - bri) * (5.8 - 3.8) / 15)) | round(1) }}
              {% elif bri > 70 and bri <= 85 %}
                {{ (8.9 - ((85 - bri) * (8.9 - 5.8) / 15)) | round(1) }}
              {% elif bri > 85 and bri <= 95 %}
                {{ (12.4 - ((95 - bri) * (12.4 - 8.9) / 10)) | round(1) }}
              {% elif bri > 95 %}
                12.8
              {% endif %}
          {% elif is_state('light.bathroom', 'off') %} 0.4
          {% else %} 0.0
          {% endif %}
        icon_template: mdi:lightbulb
        unit_of_measurement: 'W'
  # Ванная Плафон / TRÅDFRI bulb E27 opal 1000lm / энергопотребление
  - platform: integration
    source: sensor.power_light_bathroom
    name: "consumption_light_bathroom"
    unit_prefix: k
  - platform: template
    sensors:
      # Общая потребляемая мощность
      power_total:
        value_template: "{{ (states('sensor.power_smart_plug_bedroom') | float
                           + states('sensor.power_smart_plug_camera') | float
                           + states('sensor.power_light_hall_1') | float
                           + states('sensor.power_light_hall_2') | float
                           + states('sensor.power_light_livingroom_ceiling') | float
                           + states('sensor.power_light_livingroom_floor') | float
                           + states('sensor.power_light_livingroom_window') | float
                           + states('sensor.power_light_kitchen') | float
                           + states('sensor.power_light_bathroom') | float
                           + states('sensor.power_light_bedroom') | float) | round(2) }}"
        unit_of_measurement: 'W'
  # Общее энергопотребление
  - platform: integration
    source: sensor.power_total
    name: "consumption_total"
    unit_prefix: k


  # MQTT топики счетчиков потребления
  # Январь
  - platform: mqtt
    state_topic: "power/month_total/1"
    name: 'power_mqtt_total_m1'
    unit_of_measurement: ' '
  # Февраль
  - platform: mqtt
    state_topic: "power/month_total/2"
    name: 'power_mqtt_total_m2'
    unit_of_measurement: ' '
  # Март
  - platform: mqtt
    state_topic: "power/month_total/3"
    name: 'power_mqtt_total_m3'
    unit_of_measurement: ' '
  # Апрель
  - platform: mqtt
    state_topic: "power/month_total/4"
    name: 'power_mqtt_total_m4'
    unit_of_measurement: ' '
  # Май
  - platform: mqtt
    state_topic: "power/month_total/5"
    name: 'power_mqtt_total_m5'
    unit_of_measurement: ' '
  # Июнь
  - platform: mqtt
    state_topic: "power/month_total/6"
    name: 'power_mqtt_total_m6'
    unit_of_measurement: ' '
  # Июль
  - platform: mqtt
    state_topic: "power/month_total/7"
    name: 'power_mqtt_total_m7'
    unit_of_measurement: ' '
  # Август
  - platform: mqtt
    state_topic: "power/month_total/8"
    name: 'power_mqtt_total_m8'
    unit_of_measurement: ' '
  # Сентябрь
  - platform: mqtt
    state_topic: "power/month_total/9"
    name: 'power_mqtt_total_m9'
    unit_of_measurement: ' '
  # Октябрь
  - platform: mqtt
    state_topic: "power/month_total/10"
    name: 'power_mqtt_total_m10'
    unit_of_measurement: ' '
  # Ноябрь
  - platform: mqtt
    state_topic: "power/month_total/11"
    name: 'power_mqtt_total_m11'
    unit_of_measurement: ' '
  # Декабрь
  - platform: mqtt
    state_topic: "power/month_total/12"
    name: 'power_mqtt_total_m12'
    unit_of_measurement: ' '


utility_meter:
  # Розетка
  energy_monthly_smart_plug_bedroom:
    source: sensor.consumption_smart_plug_bedroom
    cycle: monthly
  # Камера
  energy_monthly_smart_plug_camera:
    source: sensor.consumption_smart_plug_camera
    cycle: monthly
  # Холл-1
  energy_monthly_light_hall_1:
    source: sensor.consumption_light_hall_1
    cycle: monthly
  # Холл-2
  energy_monthly_light_hall_2:
    source: sensor.consumption_light_hall_2
    cycle: monthly
  # Зал Люстра
  energy_monthly_light_livingroom_ceiling:
    source: sensor.consumption_light_livingroom_ceiling
    cycle: monthly
  # Зал Ночник
  energy_monthly_light_livingroom_floor:
    source: sensor.consumption_light_livingroom_floor
    cycle: monthly
  # Зал Окно
  energy_monthly_light_livingroom_window:
    source: sensor.consumption_light_livingroom_window
    cycle: monthly
  # Кухня Люстра
  energy_monthly_light_kitchen:
    source: sensor.consumption_light_kitchen
    cycle: monthly
  # Спальня Люстра
  energy_monthly_light_bedroom:
    source: sensor.consumption_light_bedroom
    cycle: monthly
  # Ванная Плафон
  energy_monthly_light_bathroom:
    source: sensor.consumption_light_bathroom
    cycle: monthly
  # Общее за месяц
  energy_monthly_total:
    source: sensor.consumption_total
    cycle: monthly
  # Общее за год
  energy_yearly_total:
    source: sensor.consumption_total
    cycle: yearly


# Автоматизации
automation:
  # Счетчик потребления за месяц
  - alias: energy_monthly_total
    initial_state: true
    trigger:
      - platform: state
        entity_id: sensor.energy_monthly_total
    action:
      - service: mqtt.publish
        data:
          topic: "power/month_total/{{ now().month }}"
          payload: "{{ (states('sensor.energy_monthly_total') | float) | round(3) }}"
          retain: true


  # Конец года, сохранение общего потребления в отдельный топик
  - alias: energy_old_year
    initial_state: true
    trigger:
      - platform: time
        at: '23:59:50'
    condition:
      - "{{ now().month == 12 and now().day == 31 }}"
    action:
      - service: mqtt.publish
        data:
          topic: "power/year_total/{{ now().year }}"
          payload: "{{ (states('sensor.energy_yearly_total') | float) | round(3) }}"
          retain: true


  # Новый год, обнуление счетчиков
  - alias: energy_new_year_reset_counter
    initial_state: true
    trigger:
      - platform: time
        at: '00:00:05'
    condition:
      - "{{ now().month == 1 and now().day == 1 }}"
    action:
      - service: mqtt.publish
        data:
          topic: "power/month_total/1"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/2"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/3"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/4"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/5"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/6"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/7"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/8"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/9"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/10"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/11"
          payload: '{{ 0.0 }}'
          retain: true
      - service: mqtt.publish
        data:
          topic: "power/month_total/12"
          payload: '{{ 0.0 }}'
          retain: true


  # Обновление utility_meter после перезагрузки HA
  - alias: update_utility_meter
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: homeassistant.update_entity
        entity_id:
          - sensor.energy_monthly_smart_plug_bedroom
          - sensor.energy_monthly_smart_plug_camera
          - sensor.energy_monthly_light_hall_1
          - sensor.energy_monthly_light_hall_2
          - sensor.energy_monthly_light_livingroom_ceiling
          - sensor.energy_monthly_light_livingroom_floor
          - sensor.energy_monthly_light_livingroom_window
          - sensor.energy_monthly_light_kitchen
          - sensor.energy_monthly_light_bedroom
          - sensor.energy_monthly_light_bathroom
          - sensor.energy_monthly_total
          - sensor.energy_yearly_total
