# Кастомизация
homeassistant:
  customize:
    sensor.gateway_illumination:
      friendly_name: Холл Освещенность


# Xiaomi Gateway Alarm
switch:
  - platform: xiaomi_gateway_alarm
    name: Xiaomi Gateway Alarm
    host: 192.168.1.x
    token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx # Gateway token
