# Кастомизация
homeassistant:
  customize:
    script.ha_backup:
      friendly_name: Резервная копия
      icon: mdi:cloud-upload


# Команды запуска shell-скриптов резервного копирования
shell_command:
  # Home Assistant
  ha_backup: ssh -p your_port root@192.168.1.x "bash /user_dir/homeassistant/shell_scripts/ha_backup.sh 2>&1 &"

# Скрипты
script:
  # Резервное копирование Home Assistant
  ha_backup:
    sequence:
      - delay: 00:00:01
      - service: shell_command.ha_backup


# Автоматизация
automation:
  # Резервное копирование Home Assistant в заданное время
  - alias: backup
    initial_state: true
    trigger:
      - platform: time
        at: '01:00:05'
    condition:
      - condition: time
        weekday:
          - mon
          - wed
          - fri
    action:
      - service: shell_command.ha_backup
