# Кастомизация
homeassistant:
  customize:
    sensor.mysql_db_size:
      friendly_name: MySQL DB
      icon: mdi:database


# Сенсор
sensor:
  # Размер базы данных MySQL
  - platform: sql
    db_url: !secret mysql_db_url
    queries:
      - name: MySQL DB size
        query: 'SELECT table_schema "database", Round(Sum((data_length + index_length) / 1024) / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="hass" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB


# Автоматизация
automation:
  # Очистка базы данных в заданное время
  - alias: database_purge
    trigger:
      platform: time
      at: '12:00:05'
    action:
      - service: recorder.purge
        data:
          keep_days: 2
          repack: true
