# Кастомизация
homeassistant:
  customize:
    sensor.command_sensor:
      friendly_name: Температура
    sensor.processor_use:
      friendly_name: Процессор
    sensor.memory_use_percent:
      friendly_name: Память
    sensor.disk_use_percent_home:
      friendly_name: SD Card
      icon: mdi:micro-sd
    sensor.disk_free_home:
      friendly_name: Свободно /home
      icon: mdi:micro-sd
    script.pi_reboot:
      friendly_name: Перезагрузка
      icon: mdi:restart
    script.pi_shutdown:
      friendly_name: Выключение
      icon: mdi:power-off


# Команды
shell_command:
  # Перезагрузка Raspberry Pi
  pi_reboot: ssh -p your_port root@192.168.1.x "sudo shutdown -r now"
  # Выключение Raspberry Pi
  pi_shutdown: ssh -p your_port root@192.168.1.x "sudo shutdown now"


# Сенсоры
sensor:
  # Raspberry Pi
  - platform: command_line
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use_percent
      - type: disk_use_percent
        arg: /home
      - type: disk_free
        arg: /home


# Скрипты
script:
  # Перезагрузка Raspberry Pi в Lovelace
  pi_reboot:
    sequence:
      - delay: 00:00:01
      - service: shell_command.pi_reboot
  # Выключение Raspberry Pi в Lovelace
  pi_shutdown:
    sequence:
      - delay: 00:00:01
      - service: shell_command.pi_shutdown
